// generated by borgogen - do not edit

export interface Kinds {
  amount: string;
  plain: `${number}`;
  ratio: number;
  coin: unknown;
  flag: string;
  p: string | null;
}

declare module "borgo-framework" {
  interface ApiRoutes {
    "GET /api/kinds": { response: Kinds };
  }
}

export {};
