// generated by borgogen - do not edit

export interface Ack {
  ok: boolean;
}

export interface POne {
  n: number;
}

export interface PTwo {
  n: number;
}

export interface PThree {
  n: number;
}

declare module "borgo-framework" {
  interface ApiRoutes {
    "POST /api/go": { response: Ack };
  }
  interface WsEvents {
    "chain/one": POne;
    "chain/three": PThree;
    "chain/two": PTwo;
  }
}

export {};
