// generated by borgogen - do not edit

export interface resp {
  a: number;
}

export interface Apiresp {
  b: string;
  c: boolean;
}

export type node = Record<string, node> | null;

declare module "borgo-framework" {
  interface ApiRoutes {
    "GET /api/alpha": { response: resp };
    "GET /api/beta": { response: Apiresp };
    "GET /api/cyc": { response: node };
    "GET /api/list": { response: Array<number> | null };
  }
}

export {};
