// generated by borgogen - do not edit
package api

import "github.com/LuigiDavideMicca/borgo"

func init() {
	borgo.Handle("POST /api/plain", CreatePlain)
	borgo.Handle("POST /api/things", CreateThing)
}
