// generated by borgogen - do not edit

export interface Blob {
  raw: string | null;
  alias: string | null;
  defined: string | null;
  arr: Array<number>;
}

export interface SelfBytes {
  text: Array<string> | null;
  ptext: Array<string> | null;
  js: Array<unknown> | null;
}

declare module "borgo-framework" {
  interface ApiRoutes {
    "GET /api/blob": { response: Blob };
    "GET /api/selfbytes": { response: SelfBytes };
  }
}

export {};
