// generated by borgogen - do not edit
package api

import "github.com/LuigiDavideMicca/borgo"

func init() {
	borgo.Handle("GET /api/empty", GetEmpty)
	borgo.Handle("GET /api/keys", GetKeys)
	borgo.Handle("GET /api/stamped", GetStamped)
	borgo.Handle("GET /api/tagged", GetTagged)
}
