// generated by borgogen - do not edit

export interface Stamp {
  nano: number;
}

export interface resp {
  at: Stamp;
}

export interface PkgResp {
  at: string;
}

declare module "borgo-framework" {
  interface ApiRoutes {
    "GET /api/local": { response: resp };
    "GET /api/pkg": { response: PkgResp };
  }
}

export {};
