// generated by borgogen - do not edit

export interface Holder {
  one: string | null;
  ptr: (string | null) | null;
  many: Array<string | null> | null;
  keyed: Record<string, string | null> | null;
  fn: ((v: string) => void) | null;
  tags: Array<string> | null;
}

declare module "borgo-framework" {
  interface ApiRoutes {
    "GET /api/soft": { response: Holder };
  }
}

export {};
