// generated by borgogen - do not edit

export interface ROne {
  n: number;
}

export interface RTwo {
  n: number;
}

export interface RThree {
  n: number;
}

declare module "borgo-framework" {
  interface ApiRoutes {
    "GET /api/chain": { response: ROne | RTwo | RThree };
  }
}

export {};
