// generated by borgogen - do not edit
package api

import "github.com/LuigiDavideMicca/borgo"

func init() {
	borgo.Handle("GET /api/alpha", Alpha)
	borgo.Handle("GET /api/beta", Beta)
	borgo.Handle("GET /api/cyc", Cyc)
	borgo.Handle("GET /api/list", List)
}
