// generated by borgogen - do not edit

export interface Thing {
  id: number;
}

declare module "borgo-framework" {
  interface ApiRoutes {
    "GET /api/fixed": { response: Thing };
  }
}

export {};
