// generated by borgogen - do not edit

export interface Me {
  username: string;
}

export interface Note {
  id: number;
  title: string;
  body: string;
  createdAt: string;
}

export interface NoteList {
  notes: Array<Note> | null;
}

// NoteCreate as encoding/json reads it, which is not
// the response it writes: a field the decoder never receives is not an
// error, and neither is one that arrives null, so every property below
// is optional and admits null whatever its Go type is.
export interface NoteCreate$Request {
  title?: string | null;
  body?: string | null;
}

export interface NoteItem {
  note: Note;
}

export interface Deleted {
  deleted: boolean;
}

declare module "borgo-framework" {
  interface ApiRoutes {
    "GET /api/events": { response: unknown };
    "POST /api/login": { response: unknown };
    "POST /api/logout": { response: unknown };
    "GET /api/me": { response: Me };
    "GET /api/notes": { response: NoteList };
    "POST /api/notes": { response: NoteItem; request: NoteCreate$Request };
    "DELETE /api/notes/{id}": { response: Deleted };
    "POST /api/register": { response: unknown };
  }
  interface WsEvents {
    "live/note-created": string;
  }
}

export {};
