// generated by borgogen - do not edit
package api

import "github.com/LuigiDavideMicca/borgo"

func init() {
	borgo.Handle("POST /api/every", PostEvery)
	borgo.Handle("POST /api/loose", PostLoose)
	borgo.Handle("POST /api/tags", PostTags)
}
