// generated by borgogen - do not edit

export interface stamp {
  nano: number;
}

declare module "borgo-framework" {
  interface ApiRoutes {
    "GET /api/one": { response: string };
    "GET /api/two": { response: stamp };
  }
}

export {};
