// generated by borgogen - do not edit

export interface Item {
  id: string;
}

export interface Nested {
  grouped: Record<string, Array<Item | null> | null> | null;
  rows: Array<Array<Item | null> | null> | null;
  chunks: Array<Array<string | null> | null> | null;
  deep: Record<string, Record<string, Array<string> | null> | null> | null;
  mixed: Record<string, Array<Record<string, number> | null> | null> | null;
}

declare module "borgo-framework" {
  interface ApiRoutes {
    "GET /api/nested/either": { response: Array<Array<Item | null> | null> | Array<Record<string, Item | null> | null> | null };
    "GET /api/nested/one": { response: Nested };
    "POST /api/nested/push": { response: Item };
  }
  interface WsEvents {
    "room/mixed": Array<Array<Item | null> | null> | Array<Record<string, Array<string> | null> | null> | null;
  }
}

export {};
