// generated by borgogen - do not edit
package api

import "github.com/LuigiDavideMicca/borgo"

func init() {
	borgo.Handle("GET /api/ring", GetRing)
	borgo.Handle("GET /api/tree", GetTree)
	borgo.Handle("GET /api/wallet", GetWallet)
}
