// generated by borgogen - do not edit

export interface Price {
  amount: string;
  ship: string;
  raw: number;
}

declare module "borgo-framework" {
  interface ApiRoutes {
    "GET /api/price": { response: Price };
  }
}

export {};
