// generated by borgogen - do not edit

// Filter as encoding/json reads it, which is not
// the response it writes: a field the decoder never receives is not an
// error, and neither is one that arrives null, so every property below
// is optional and admits null whatever its Go type is.
export interface Filter$Request {
  q?: string | null;
}

export interface User {
  name: string;
}

declare module "borgo-framework" {
  interface ApiRoutes {
    "POST /api/login": { response: unknown };
    "GET /api/notfound": { response: unknown };
    "GET /api/users": { response: User; request: Filter$Request };
  }
}

export {};
