// generated by borgogen - do not edit

export interface Filter {
  q: string;
}

export interface User {
  name: string;
}

declare module "borgo-framework" {
  interface ApiRoutes {
    "POST /api/login": { response: unknown };
    "GET /api/notfound": { response: unknown };
    "GET /api/users": { response: User; request: Filter };
  }
}

export {};
