// generated by borgogen - do not edit

export interface TierBox {
  one: number;
}

export interface PtrText {
  one: number;
  many: Array<string> | null;
  keyed: Record<string, number> | null;
  deep: TierBox;
}

export interface Resp {
  id: string;
  lvl: string;
  addr: string;
  keyed: Record<string, number> | null;
  plain: number;
}

declare module "borgo-framework" {
  interface ApiRoutes {
    "GET /api/ptrtext": { response: PtrText };
    "GET /api/resp": { response: Resp };
  }
}

export {};
