// reads the newest run in ../results and every app manifest, and writes
// data.gen.ts - the one module the page imports. build-time, so the page
// itself ships zero javascript and the numbers a reader sees are the
// committed json's by construction; bench/test/site.test.ts holds that
// equality mechanically.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const resultsDir = join(import.meta.dir, "..", "results");
const appsDir = join(import.meta.dir, "..", "apps");

type RawRun = {
  environment: {
    capturedAt: string;
    host: {
      platform: string;
      osType: string;
      osRelease: string;
      cpuModel: string;
      cpuCount: number;
      totalMemBytes: number;
    };
    versions: Record<string, string>;
    repo: { commit: string; dirty: boolean; borgoVersion: string };
    loadTool: { name: string; version: string };
    note?: string;
    machineBusyWarning?: string;
  };
  config: {
    connections: number;
    durationSeconds: number;
    warmupSeconds: number;
    runs: number;
    memoryConnections: number;
  };
  results: Array<{
    app: string;
    manifest: { framework: string; language: string; runtime: string; notes?: string };
    status: string;
    error?: string;
    scenarios: Array<{
      scenario: string;
      status: string;
      load?: {
        median: {
          requestsPerSec: number;
          successRate: number;
          latencyMs: { p50: number; p99: number };
        };
      };
      memory?: {
        idleRssBytes: number;
        deltaBytes: number;
        bytesPerConnection: number;
        reliable: boolean;
      };
    }>;
  }>;
};

const runs = readdirSync(resultsDir)
  .filter((f) => f.startsWith("run-") && f.endsWith(".json"))
  .sort();
if (runs.length === 0) throw new Error("no run-*.json in bench/results - run the harness first");
const newest = runs.at(-1)!;
const raw = JSON.parse(readFileSync(join(resultsDir, newest), "utf8")) as RawRun;

// the honesty list: apps that exist but were not measured, with their reason
const notMeasured: Array<{ name: string; reason: string }> = [];
for (const dir of readdirSync(appsDir, { withFileTypes: true })) {
  if (!dir.isDirectory()) continue;
  const manifest = JSON.parse(
    readFileSync(join(appsDir, dir.name, "bench.manifest.json"), "utf8"),
  ) as { name: string; status: string; todo?: string };
  if (manifest.status === "stub") {
    notMeasured.push({ name: manifest.name, reason: `stub: ${manifest.todo ?? "not implemented"}` });
  } else if (!raw.results.some((r) => r.app === manifest.name)) {
    notMeasured.push({ name: manifest.name, reason: "not part of this run" });
  }
}
for (const r of raw.results) {
  if (r.status !== "ok") notMeasured.push({ name: r.app, reason: r.error ?? r.status });
}
// readdir order is platform-dependent (alphabetical on windows, inode order on
// linux), and the freshness test byte-compares this file against a regeneration
notMeasured.sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));

const data = {
  file: newest,
  environment: {
    capturedAt: raw.environment.capturedAt,
    host: raw.environment.host,
    versions: raw.environment.versions,
    repo: raw.environment.repo,
    loadTool: raw.environment.loadTool,
    note: raw.environment.note ?? null,
  },
  config: raw.config,
  apps: raw.results
    .filter((r) => r.status === "ok")
    .map((r) => ({
      name: r.app,
      framework: r.manifest.framework,
      language: r.manifest.language,
      runtime: r.manifest.runtime,
      notes: r.manifest.notes ?? null,
      load: Object.fromEntries(
        r.scenarios
          .filter((s) => s.status === "ok" && s.load)
          .map((s) => [
            s.scenario,
            {
              rps: s.load!.median.requestsPerSec,
              p50: s.load!.median.latencyMs.p50,
              p99: s.load!.median.latencyMs.p99,
              successRate: s.load!.median.successRate,
            },
          ]),
      ),
      memory:
        r.scenarios.find((s) => s.scenario === "memory-conn" && s.status === "ok" && s.memory)
          ?.memory ?? null,
    })),
  notMeasured,
};

writeFileSync(
  join(import.meta.dir, "data.gen.ts"),
  `// generated by generate.ts from bench/results/${newest} - do not edit\n` +
    `export const run = ${JSON.stringify(data, null, 2)} as const;\n`,
);
console.log(`data.gen.ts <- ${newest} (${data.apps.length} apps, ${notMeasured.length} not measured)`);
