// generated by borgogen - do not edit

export interface Box {
  code: string | null;
  free: unknown;
  many: Array<string | null> | null;
}

declare module "borgo-framework" {
  interface ApiRoutes {
    "GET /api/box": { response: Box };
  }
}

export {};
