// generated by borgogen - do not edit

export interface Empty {
  items: Array<number> | null;
  m: Record<string, number> | null;
  raw: string | null;
  nest: Array<Array<string> | null> | null;
  named: Array<string> | null;
  arr: Array<number>;
}

export interface Keys {
  fees: unknown;
  sizes: Record<string, number> | null;
}

export interface MapBoth {
  m: Record<string, number> | null;
}

export interface Nums {
  n: number;
  np: number | null;
  ns: Array<number> | null;
  amt: string;
}

export interface PM {
  x: number;
}

export interface PMHolder {
  one: unknown | PM;
  many: Array<unknown | PM> | null;
  ptr: unknown | PM | null;
  keyed: Record<string, unknown | PM> | null;
}

export interface Stamped {
  at: unknown;
  plain: { n: number };
}

export interface Tagged {
  l: string;
  p: string | { N: number; extra: number };
  many: Array<string | { N: number; extra: number }> | null;
}

export interface Uint8Marshal {
  u: unknown;
}

declare module "borgo-framework" {
  interface ApiRoutes {
    "GET /api/either": { response: Array<string> | Array<number> | null };
    "GET /api/empty": { response: Empty };
    "GET /api/keys": { response: Keys };
    "GET /api/mapboth": { response: MapBoth };
    "GET /api/nums": { response: Nums };
    "GET /api/pm": { response: PMHolder };
    "GET /api/stamped": { response: Stamped };
    "GET /api/tagged": { response: Tagged };
    "GET /api/uint8": { response: Uint8Marshal };
  }
}

export {};
