// generated by borgogen - do not edit

export interface Empty {
  items: Array<number> | null;
  m: Record<string, number> | null;
  raw: string | null;
  nest: Array<Array<string> | null> | null;
  named: Array<string> | null;
  arr: Array<number>;
}

export interface Keys {
  fees: unknown;
  sizes: Record<string, number> | null;
}

export interface Stamped {
  at: unknown;
  plain: { n: number };
}

export interface Tagged {
  l: string;
  p: string | { N: number; extra: number };
  many: Array<string | { N: number; extra: number }> | null;
}

declare module "borgo-framework" {
  interface ApiRoutes {
    "GET /api/empty": { response: Empty };
    "GET /api/keys": { response: Keys };
    "GET /api/stamped": { response: Stamped };
    "GET /api/tagged": { response: Tagged };
  }
}

export {};
