// borgo deploy init <target>: writes the deploy guide's blessed config for
// caddy, nginx, systemd or compose into the project, templated with the
// app's name and ports. never overwrites without --force.
import { randomBytes } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { banner, c, g } from "./colors";

export type DeployContext = {
  name: string;
  port: string;
  apiPort: string;
  /**
   * The signing key the app already has, read from its `.env` - `null` when it
   * has none. Not a value to copy around: what the generated configs need to
   * know is whether the app signs sessions at all, and whether a key is
   * already being supplied from somewhere they must not override.
   */
  secret?: string | null;
};

// session.go refuses a SESSION_SECRET shorter than this, so anything under it
// is not a placeholder to fill in later - it is an app whose every auth route
// answers 500
export const SESSION_SECRET_MIN = 32;

// 48 base64url characters out of the CSPRNG: over the floor, and safe to put
// on a systemd `Environment=` line unquoted (no spaces, no `%`, no newline)
export function randomSecret(): string {
  return randomBytes(36).toString("base64url");
}

// what the app is already signing with. a real environment variable beats
// `.env` in bun, so a config that sets SESSION_SECRET to anything else - a
// placeholder, or a fresh random key - silently overrides the one
// `create-borgo` generated and invalidates every session the app ever issued.
export function envSecret(dir = "."): string | null {
  let raw: string;
  try {
    raw = readFileSync(join(dir, ".env"), "utf8");
  } catch {
    return null;
  }
  const value = raw
    .match(/^\s*(?:export\s+)?SESSION_SECRET\s*=\s*(.*)$/m)?.[1]
    ?.trim()
    .replace(/^(["'])(.*)\1$/, "$2");
  return value && value.length >= SESSION_SECRET_MIN ? value : null;
}

/**
 * `borgo <deploy|pwa> init [target] [--force]`, and nothing else.
 *
 * The old parser was `argv.filter(a => !a.startsWith("--"))`, which drops a
 * flag and keeps its value: `deploy init nginx --port 8080` read `8080` as a
 * second positional and silently wrote the default-port config, and
 * `deploy init --port 8080 nginx` took `8080` as the target. Unknown options
 * and surplus arguments are refused by name instead.
 */
export type InitArgv = { ok: true; target?: string; force: boolean } | { ok: false; reason: string };

export function parseInitArgv(argv: string[], maxPositionals: number): InitArgv {
  const positionals: string[] = [];
  let force = false;
  for (const arg of argv) {
    if (arg === "--force") {
      force = true;
      continue;
    }
    // parsed globally by the cli itself, and legal after any command
    if (arg === "--tailwind") continue;
    if (arg.startsWith("-")) return { ok: false, reason: `unknown option "${arg}"` };
    positionals.push(arg);
  }
  const [sub, ...rest] = positionals;
  if (sub !== "init") {
    return { ok: false, reason: sub ? `unknown subcommand "${sub}"` : "missing subcommand" };
  }
  if (rest.length > maxPositionals) {
    return { ok: false, reason: `unexpected argument "${rest[maxPositionals]}"` };
  }
  return { ok: true, target: rest[0], force };
}

export function caddyfile({ name, port }: DeployContext): string {
  return [
    `# ${name}: generated by borgo deploy init - replace example.com with your domain.`,
    "# borgo compresses responses itself, so no encode directive here.",
    "example.com {",
    `    reverse_proxy localhost:${port}`,
    "}",
    "",
  ].join("\n");
}

export function nginxConf({ name, port }: DeployContext): string {
  return [
    `# ${name}: generated by borgo deploy init - replace example.com with your domain`,
    "# and uncomment the two certificate lines (or drop to `listen 80;` behind",
    "# another terminator). nginx -t fails on `listen 443 ssl` with no certificate,",
    "# so those two lines are the one edit between this file and a running nginx.",
    "# upgrade headers keep websockets alive, proxy_buffering off keeps sse streaming,",
    "# and borgo compresses responses itself (gzip off is nginx's default).",
    "",
    "# `Connection: upgrade` belongs on a request that asked to upgrade, and on",
    "# no other: a fixed value sends it on every proxied request, which stops",
    "# nginx from keeping the upstream connection alive and hands borgo a",
    "# hop-by-hop header it has to strip. this map answers `upgrade` only when",
    "# the client sent an Upgrade header, and `close` otherwise. it sits at http",
    "# level, which is where sites-enabled is included from.",
    "map $http_upgrade $connection_upgrade {",
    "    default upgrade;",
    "    ''      close;",
    "}",
    "",
    "server {",
    "    listen 443 ssl;",
    "    server_name example.com;",
    "",
    "    # certbot writes these two; without them nginx refuses to start",
    "    # ssl_certificate     /etc/letsencrypt/live/example.com/fullchain.pem;",
    "    # ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem;",
    "",
    // nginx's default is 1m, and borgo's own limit is 32m (BORGO_MAX_BODY):
    // leaving the two disagreeing means an app with uploads works under
    // `borgo start` and 413s behind the config borgo generated for it
    "    # borgo's own limit is 32m (BORGO_MAX_BODY); nginx defaults to 1m and",
    "    # would 413 an upload the app is happy to accept",
    "    client_max_body_size 32m;",
    "",
    "    location / {",
    `        proxy_pass http://localhost:${port};`,
    "        proxy_http_version 1.1;",
    "        proxy_set_header Upgrade $http_upgrade;",
    "        proxy_set_header Connection $connection_upgrade;",
    "        proxy_set_header Host $host;",
    // nginx adds no forwarding header on its own, and borgo authorizes
    // /__borgo/publish as "from loopback and not forwarded". Behind a proxy on
    // the same box every request arrives from loopback, so without this line
    // the second half of that test never fires and anyone on the internet can
    // broadcast into every subscribed browser. Caddy sets it by default, which
    // is why only this config had the hole.
    "        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;",
    "        proxy_set_header X-Forwarded-Proto $scheme;",
    "        proxy_buffering off;",
    "        proxy_read_timeout 1h;",
    "    }",
    "}",
    "",
  ].join("\n");
}

export function systemdUnit({ name, port, apiPort, secret }: DeployContext): string {
  // `Environment=SESSION_SECRET=change-me` was nine bytes, under session.go's
  // 32-character floor, so every auth route answered 500 - and because a real
  // environment variable beats `.env` in bun, the unit borgo wrote also
  // overrode the random key create-borgo had generated. An app that worked
  // locally, broken by its own deploy config. So: when the app already has a
  // key, the unit deliberately sets nothing and says why; when it does not,
  // the key written here is a real one.
  const session = secret
    ? [
        "# SESSION_SECRET is deliberately not set here: bun loads .env from the",
        `# working directory, so /srv/${name}/.env is the single source of the`,
        "# key. An Environment= line would win over it and invalidate every",
        "# session the app has already issued - copy .env to the server instead.",
      ]
    : [
        "# generated by borgo deploy init, unique to this file. borgo refuses a",
        "# SESSION_SECRET under 32 characters, so a placeholder here would be an",
        "# app whose every login answers 500. shipping a .env instead? delete",
        "# this line: bun reads .env from the working directory, and a real",
        "# environment variable would override it.",
        `Environment=SESSION_SECRET=${randomSecret()}`,
      ];
  return [
    "[Unit]",
    `Description=${name} (borgo app)`,
    "After=network.target",
    "",
    "[Service]",
    `WorkingDirectory=/srv/${name}`,
    // systemd requires an absolute path, so this cannot be a bare `bun`. it is
    // where a system-wide install puts it; the official installer script puts
    // it in the installing user's ~/.bun/bin instead
    "# absolute path is systemd's rule, not borgo's: check yours with `command -v bun`.",
    "# the official installer writes ~/.bun/bin/bun, which is not readable by User=",
    "# below - copy or symlink it somewhere system-wide, or point this line at it.",
    "ExecStart=/usr/local/bin/bun run start",
    "Environment=NODE_ENV=production",
    `Environment=PORT=${port}`,
    `Environment=API_PORT=${apiPort}`,
    ...session,
    "# bun's outbound fetch pool defaults to 256, which ceilings concurrent",
    "# proxied requests - event streams above all - see docs/realtime.md",
    "Environment=BUN_CONFIG_MAX_HTTP_REQUESTS=16384",
    "Restart=on-failure",
    "User=www-data",
    "",
    "[Install]",
    "WantedBy=multi-user.target",
    "",
  ].join("\n");
}

export function composeYml({ port, secret }: DeployContext): string {
  // an app that signs sessions gets the same required declaration the `full`
  // template ships: docker compose interpolates it from the .env beside this
  // file (which the image never sees - .dockerignore excludes it), and `:?`
  // stops the deploy with a message rather than producing an app whose every
  // login answers 500. an app with no key gets no line to override: this file
  // used to replace a correct one with a comment.
  const session = secret
    ? [
        "      # read from the .env beside this file, which docker compose",
        "      # interpolates and the image never receives (.dockerignore",
        "      # excludes it). required on purpose: a missing key must stop the",
        "      # deploy, not turn up later as a 500 on every login.",
        '      SESSION_SECRET: "${SESSION_SECRET:?missing - create-borgo writes one into .env, or generate one with openssl rand -base64 48}"',
      ]
    : [
        "      # this app signs no sessions yet. adding borgo.SetSession later?",
        "      # it needs SESSION_SECRET (32+ random characters) or every session",
        "      # route answers 500 - put it in the .env beside this file and",
        '      # declare it here as: SESSION_SECRET: "${SESSION_SECRET:?missing}"',
      ];
  return [
    "services:",
    "  app:",
    "    build: .",
    "    ports:",
    `      - "${port}:${port}"`,
    "    environment:",
    "      NODE_ENV: production",
    `      PORT: "${port}"`,
    ...session,
    "      # bun's outbound fetch pool defaults to 256, which ceilings",
    "      # concurrent event streams - see docs/realtime.md",
    '      BUN_CONFIG_MAX_HTTP_REQUESTS: "16384"',
    "    restart: unless-stopped",
    // no volume: the templates deliberately ship none, because nothing in them
    // persists anything yet, and a mount docker creates root-owned is a
    // permission error waiting for the first app that uses it. the scaffolded
    // Dockerfiles already prepare /data, so adding one is two blocks here.
    "# nothing here persists yet, so there is no volume. swapping the in-memory",
    "# stores for a real database? the scaffolded Dockerfile already creates",
    "# /data owned by the image's user, so this is the whole change:",
    "#   environment:",
    "#     DB_PATH: /data/app.db",
    "#   volumes:",
    "#     - data:/data",
    "# volumes:",
    "#   data:",
    "",
  ].join("\n");
}

export const targets: Record<string, { file: string; render: (ctx: DeployContext) => string; next: (ctx: DeployContext) => string }> = {
  caddy: {
    file: "Caddyfile",
    render: caddyfile,
    next: () => "set your domain, then: caddy run --config Caddyfile",
  },
  nginx: {
    file: "site.conf",
    render: nginxConf,
    next: ({ name }) => `set your domain and certs, then link it: /etc/nginx/sites-enabled/${name}.conf`,
  },
  systemd: {
    file: "borgo.service",
    render: systemdUnit,
    next: ({ name }) =>
      `copy to /etc/systemd/system/${name}.service, then: systemctl enable --now ${name}`,
  },
  compose: {
    file: "docker-compose.yml",
    render: composeYml,
    next: () => "docker compose up -d",
  },
};

export function projectContext(dir = "."): DeployContext {
  let name = "borgo-app";
  try {
    const pkg = JSON.parse(readFileSync(join(dir, "package.json"), "utf8")) as { name?: string };
    if (pkg.name) name = pkg.name.replace(/[^a-zA-Z0-9._-]+/g, "-").replace(/^-+|-+$/g, "") || name;
  } catch {}
  return {
    name,
    port: process.env.PORT || "3000",
    apiPort: process.env.API_PORT || "3501",
    secret: envSecret(dir),
  };
}

export function deployInit(target: string | undefined, force = false, dir = "."): number {
  console.log(`\n  ${banner("deploy")}\n`);
  const known = Object.keys(targets).join("|");
  if (!target || !targets[target]) {
    if (target) console.log(`  ${c.red(g.err)} unknown target "${target}"`);
    console.log(`  usage: borgo deploy init <${known}> [--force]\n`);
    return 1;
  }

  const { file, render, next } = targets[target];
  const path = join(dir, file);
  if (existsSync(path) && !force) {
    console.log(`  ${c.red(g.err)} ${file} already exists ${c.dim(`${g.dot} rerun with --force to overwrite`)}\n`);
    return 1;
  }

  const ctx = projectContext(dir);
  try {
    writeFileSync(path, render(ctx));
  } catch (error) {
    console.log(`  ${c.red(g.err)} cannot write ${file}: ${error instanceof Error ? error.message : error}\n`);
    return 1;
  }
  console.log(`  ${c.sage(g.ok)} ${file} ${c.dim(`${g.dot} ${target} config for ${ctx.name} on port ${ctx.port}`)}`);
  console.log(`  ${c.terracotta(g.arrow)} ${next(ctx)}\n`);
  return 0;
}
