// borgo deploy init <target>: writes the deploy guide's blessed config for
// caddy, nginx, systemd or compose into the project, templated with the
// app's name and ports. never overwrites without --force.
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { banner, c, g } from "./colors";

export type DeployContext = {
  name: string;
  port: string;
  apiPort: string;
};

export function caddyfile({ name, port }: DeployContext): string {
  return [
    `# ${name}: generated by borgo deploy init - replace example.com with your domain.`,
    "# borgo compresses responses itself, so no encode directive here.",
    "example.com {",
    `    reverse_proxy localhost:${port}`,
    "}",
    "",
  ].join("\n");
}

export function nginxConf({ name, port }: DeployContext): string {
  return [
    `# ${name}: generated by borgo deploy init - replace example.com with your domain`,
    "# and uncomment the two certificate lines (or drop to `listen 80;` behind",
    "# another terminator). nginx -t fails on `listen 443 ssl` with no certificate,",
    "# so those two lines are the one edit between this file and a running nginx.",
    "# upgrade headers keep websockets alive, proxy_buffering off keeps sse streaming,",
    "# and borgo compresses responses itself (gzip off is nginx's default).",
    "server {",
    "    listen 443 ssl;",
    "    server_name example.com;",
    "",
    "    # certbot writes these two; without them nginx refuses to start",
    "    # ssl_certificate     /etc/letsencrypt/live/example.com/fullchain.pem;",
    "    # ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem;",
    "",
    // nginx's default is 1m, and borgo's own limit is 32m (BORGO_MAX_BODY):
    // leaving the two disagreeing means an app with uploads works under
    // `borgo start` and 413s behind the config borgo generated for it
    "    # borgo's own limit is 32m (BORGO_MAX_BODY); nginx defaults to 1m and",
    "    # would 413 an upload the app is happy to accept",
    "    client_max_body_size 32m;",
    "",
    "    location / {",
    `        proxy_pass http://localhost:${port};`,
    "        proxy_http_version 1.1;",
    "        proxy_set_header Upgrade $http_upgrade;",
    '        proxy_set_header Connection "upgrade";',
    "        proxy_set_header Host $host;",
    // nginx adds no forwarding header on its own, and borgo authorizes
    // /__borgo/publish as "from loopback and not forwarded". Behind a proxy on
    // the same box every request arrives from loopback, so without this line
    // the second half of that test never fires and anyone on the internet can
    // broadcast into every subscribed browser. Caddy sets it by default, which
    // is why only this config had the hole.
    "        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;",
    "        proxy_set_header X-Forwarded-Proto $scheme;",
    "        proxy_buffering off;",
    "        proxy_read_timeout 1h;",
    "    }",
    "}",
    "",
  ].join("\n");
}

export function systemdUnit({ name, port, apiPort }: DeployContext): string {
  return [
    "[Unit]",
    `Description=${name} (borgo app)`,
    "After=network.target",
    "",
    "[Service]",
    `WorkingDirectory=/srv/${name}`,
    "ExecStart=/usr/local/bin/bun run start",
    "Environment=NODE_ENV=production",
    `Environment=PORT=${port}`,
    `Environment=API_PORT=${apiPort}`,
    "Environment=SESSION_SECRET=change-me",
    "# bun's outbound fetch pool defaults to 256, which ceilings concurrent",
    "# proxied requests - event streams above all - see docs/realtime.md",
    "Environment=BUN_CONFIG_MAX_HTTP_REQUESTS=16384",
    "Restart=on-failure",
    "User=www-data",
    "",
    "[Install]",
    "WantedBy=multi-user.target",
    "",
  ].join("\n");
}

export function composeYml({ port }: DeployContext): string {
  return [
    "services:",
    "  app:",
    "    build: .",
    "    ports:",
    `      - "${port}:${port}"`,
    "    environment:",
    "      # SESSION_SECRET: use-a-long-random-string",
    // the volume below is created root-owned by docker, and the images borgo
    // scaffolds drop to `USER bun`: uncommenting DB_PATH without preparing the
    // directory in the Dockerfile is a permission-denied at startup, every time
    "      # DB_PATH needs /data writable by the image's user. In the Dockerfile,",
    "      # before `USER bun`: RUN mkdir -p /data && chown bun:bun /data",
    "      # DB_PATH: /data/app.db",
    "      NODE_ENV: production",
    `      PORT: "${port}"`,
    "      # bun's outbound fetch pool defaults to 256, which ceilings",
    "      # concurrent event streams - see docs/realtime.md",
    '      BUN_CONFIG_MAX_HTTP_REQUESTS: "16384"',
    "    volumes:",
    "      - data:/data",
    "    restart: unless-stopped",
    "",
    "volumes:",
    "  data:",
    "",
  ].join("\n");
}

export const targets: Record<string, { file: string; render: (ctx: DeployContext) => string; next: (ctx: DeployContext) => string }> = {
  caddy: {
    file: "Caddyfile",
    render: caddyfile,
    next: () => "set your domain, then: caddy run --config Caddyfile",
  },
  nginx: {
    file: "site.conf",
    render: nginxConf,
    next: ({ name }) => `set your domain and certs, then link it: /etc/nginx/sites-enabled/${name}.conf`,
  },
  systemd: {
    file: "borgo.service",
    render: systemdUnit,
    next: ({ name }) =>
      `copy to /etc/systemd/system/${name}.service, then: systemctl enable --now ${name}`,
  },
  compose: {
    file: "docker-compose.yml",
    render: composeYml,
    next: () => "docker compose up -d",
  },
};

export function projectContext(dir = "."): DeployContext {
  let name = "borgo-app";
  try {
    const pkg = JSON.parse(readFileSync(join(dir, "package.json"), "utf8")) as { name?: string };
    if (pkg.name) name = pkg.name.replace(/[^a-zA-Z0-9._-]+/g, "-").replace(/^-+|-+$/g, "") || name;
  } catch {}
  return {
    name,
    port: process.env.PORT || "3000",
    apiPort: process.env.API_PORT || "3501",
  };
}

export function deployInit(target: string | undefined, force = false, dir = "."): number {
  console.log(`\n  ${banner("deploy")}\n`);
  const known = Object.keys(targets).join("|");
  if (!target || !targets[target]) {
    if (target) console.log(`  ${c.red(g.err)} unknown target "${target}"`);
    console.log(`  usage: borgo deploy init <${known}> [--force]\n`);
    return 1;
  }

  const { file, render, next } = targets[target];
  const path = join(dir, file);
  if (existsSync(path) && !force) {
    console.log(`  ${c.red(g.err)} ${file} already exists ${c.dim(`${g.dot} rerun with --force to overwrite`)}\n`);
    return 1;
  }

  const ctx = projectContext(dir);
  try {
    writeFileSync(path, render(ctx));
  } catch (error) {
    console.log(`  ${c.red(g.err)} cannot write ${file}: ${error instanceof Error ? error.message : error}\n`);
    return 1;
  }
  console.log(`  ${c.sage(g.ok)} ${file} ${c.dim(`${g.dot} ${target} config for ${ctx.name} on port ${ctx.port}`)}`);
  console.log(`  ${c.terracotta(g.arrow)} ${next(ctx)}\n`);
  return 0;
}
