// borgo deploy init <target>: caddy, nginx, systemd or compose config templated
// with the app's name and ports. never overwrites without --force
import { randomBytes } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { banner, c, g } from "./colors";

export type DeployContext = {
  name: string;
  port: string;
  apiPort: string;
  // the app's own key from `.env`, `null` when none: the configs only need to
  // know whether a key is already supplied from somewhere they must not override
  secret?: string | null;
};

// session.go refuses a SESSION_SECRET shorter than this at startup (an unset
// one only warns, and the auth routes answer 500 until it is set)
export const SESSION_SECRET_MIN = 32;
// 48 base64url characters: over the floor, and safe unquoted on a systemd
// `Environment=` line (no spaces, no `%`, no newline)
export function randomSecret(): string {
  return randomBytes(36).toString("base64url");
}

// KEY=value, optional `export`, optional quotes: not a dotenv implementation
export function envFile(dir = "."): Record<string, string> {
  let raw: string;
  try {
    raw = readFileSync(join(dir, ".env"), "utf8");
  } catch {
    return {};
  }
  const out: Record<string, string> = {};
  for (const line of raw.split("\n")) {
    const found = line.match(/^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/);
    if (found) out[found[1]] = found[2].trim().replace(/^(["'])(.*)\1$/, "$2");
  }
  return out;
}

// a real environment variable beats `.env` in bun, so a config that sets
// SESSION_SECRET to anything else silently overrides the one create-borgo
// generated and invalidates every session the app ever issued
export function envSecret(dir = "."): string | null {
  const value = envFile(dir).SESSION_SECRET;
  return value && value.length >= SESSION_SECRET_MIN ? value : null;
}

export type InitArgv = { ok: true; target?: string; force: boolean } | { ok: false; reason: string };

// `--tailwind` is read off the whole argv by cli.ts before dispatching, so it is
// global. `--debug` is global only here: deploy init and pwa init go through
// parseInitArgv, which skips `--tailwind` alone and refuses `--debug`
export const GLOBAL_FLAGS = ["--tailwind", "--debug"] as const;
export const COMMAND_FLAGS: Record<string, readonly string[]> = {
  dev: [],
  build: [],
  // the split deployment: run the front server, point API_URL at an api elsewhere
  start: ["--front-only"],
  export: [],
  doctor: [],
};

// null when every argument is one this command knows. an unrecognised
// command is not this function's to judge: the cli's default branch prints usage
export function unknownArg(command: string, argv: readonly string[]): string | null {
  const known = COMMAND_FLAGS[command];
  if (!known) return null;
  for (const arg of argv) {
    if (!arg.startsWith("-")) return `unexpected argument "${arg}"`;
    if (!known.includes(arg) && !GLOBAL_FLAGS.includes(arg as (typeof GLOBAL_FLAGS)[number])) {
      return `unknown option "${arg}"`;
    }
  }
  return null;
}

export function parseInitArgv(argv: string[], maxPositionals: number): InitArgv {
  const positionals: string[] = [];
  let force = false;
  for (const arg of argv) {
    if (arg === "--force") {
      force = true;
      continue;
    }
    // read off the whole argv by cli.ts, legal after any command
    if (arg === "--tailwind") continue;
    if (arg.startsWith("-")) return { ok: false, reason: `unknown option "${arg}"` };
    positionals.push(arg);
  }
  const [sub, ...rest] = positionals;
  if (sub !== "init") {
    return { ok: false, reason: sub ? `unknown subcommand "${sub}"` : "missing subcommand" };
  }
  if (rest.length > maxPositionals) {
    return { ok: false, reason: `unexpected argument "${rest[maxPositionals]}"` };
  }
  return { ok: true, target: rest[0], force };
}

// borgo.Bind caps a JSON body at 1 MiB (bindLimit in borgo.go) and answers 413
// above it; a route that takes more says so with borgo.BindMax, and then this
// line moves with it, in both generated proxies
export const BODY_LIMIT = 1024 * 1024;

// `tls internal` is the default, not a suggestion: caddy's automatic https has
// no local fallback, so `example.com { }` without it opens a real ACME order
// against Let's Encrypt for a domain the operator does not own and retries
// the failure for 30 days, with rate limits charged to the operator's account
export function caddyfile({ name, port }: DeployContext): string {
  return [
    `# ${name}: generated by borgo deploy init.`,
    "# as written this runs offline: a certificate from caddy's own local CA.",
    "# going live is two edits - your domain instead of example.com, and delete",
    "# the tls line, after which caddy gets a public certificate on its own.",
    "# borgo compresses responses itself, so no encode directive here.",
    "example.com {",
    "    # local CA, no ACME, no network. delete when the domain above is real.",
    "    tls internal",
    "    # borgo.Bind reads at most 1 MiB; a route that takes more uses",
    "    # borgo.BindMax, and this line has to be raised with it.",
    "    request_body {",
    "        max_size 1MiB",
    "    }",
    `    reverse_proxy localhost:${port} {`,
    // set from the peer, never appended: at the edge an inbound X-Forwarded-For
    // or X-Real-IP is the client's invention
    "        # written from the peer, never from what the client sent",
    "        header_up X-Real-IP {remote_host}",
    "        header_up X-Forwarded-For {remote_host}",
    "    }",
    "}",
    "",
  ].join("\n");
}

export function nginxConf({ name, port }: DeployContext): string {
  return [
    `# ${name}: generated by borgo deploy init - replace example.com with your domain`,
    "# and uncomment the two certificate lines (or drop to `listen 80;` behind",
    "# another terminator). nginx -t fails on `listen 443 ssl` with no certificate,",
    "# so those two lines are the one edit between this file and a running nginx.",
    "# upgrade headers keep websockets alive, proxy_buffering off keeps sse streaming,",
    "# and borgo compresses responses itself (gzip off is nginx's default).",
    "",
    "# `Connection: upgrade` belongs on a request that asked to upgrade, and on",
    "# no other: a fixed value sends it on every proxied request, which stops",
    "# nginx from keeping the upstream connection alive and hands borgo a",
    "# hop-by-hop header it has to strip. this map answers `upgrade` only when",
    "# the client sent an Upgrade header, and `close` otherwise. it sits at http",
    "# level, which is where sites-enabled is included from.",
    "map $http_upgrade $connection_upgrade {",
    "    default upgrade;",
    "    ''      close;",
    "}",
    "",
    "server {",
    "    listen 443 ssl;",
    "    server_name example.com;",
    "    server_tokens off;",
    "",
    "    # certbot writes these two; without them nginx refuses to start",
    "    # ssl_certificate     /etc/letsencrypt/live/example.com/fullchain.pem;",
    "    # ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem;",
    "",
    // the same 1 MiB the Caddyfile caps at
    "    # borgo.Bind reads at most 1 MiB; a route that takes more uses",
    "    # borgo.BindMax, and this line has to be raised with it.",
    "    client_max_body_size 1m;",
    "",
    "    location / {",
    `        proxy_pass http://localhost:${port};`,
    "        proxy_http_version 1.1;",
    "        proxy_set_header Upgrade $http_upgrade;",
    "        proxy_set_header Connection $connection_upgrade;",
    "        proxy_set_header Host $host;",
    // nginx adds no forwarding header on its own, and borgo authorizes
    // /__borgo/publish as "from loopback and not forwarded": behind a proxy on
    // the same box every request is from loopback, so without these lines
    // anyone on the internet can publish. set, never appended: at the edge an
    // inbound chain is the client's invention. behind a proxy that is not ours,
    // add it to set_real_ip_from (nginx) / trusted_proxies (caddy)
    "        # written from the peer, never from what the client sent",
    "        proxy_set_header X-Real-IP $remote_addr;",
    "        proxy_set_header X-Forwarded-For $remote_addr;",
    "        proxy_set_header X-Forwarded-Proto $scheme;",
    "        proxy_buffering off;",
    "        proxy_read_timeout 1h;",
    "    }",
    "}",
    "",
  ].join("\n");
}

export function systemdUnit({ name, port, apiPort }: DeployContext): string {
  // the key is never written here: a unit file lands in the project directory,
  // is world-readable under /etc/systemd/system and shows in `systemctl show`
  const session = [
    "# secrets stay in the app's gitignored .env and never in this file. the",
    "# leading dash tolerates its absence; what the file sets wins over the",
    "# Environment= lines above, which is why the ports come from it too.",
    `EnvironmentFile=-/srv/${name}/.env`,
  ];
  // 9.0 UNSAFE from `systemd-analyze security` without this set. MemoryDenyWriteExecute
  // is deliberately absent: bun jits, and it would refuse to start
  const hardening = [
    "NoNewPrivileges=yes",
    "ProtectSystem=strict",
    "ProtectHome=yes",
    "PrivateTmp=yes",
    "PrivateDevices=yes",
    "ProtectKernelTunables=yes",
    "ProtectControlGroups=yes",
    "ProtectKernelModules=yes",
    "ProtectClock=yes",
    "ProtectHostname=yes",
    "RestrictSUIDSGID=yes",
    "RestrictNamespaces=yes",
    "RestrictRealtime=yes",
    "LockPersonality=yes",
    "SystemCallArchitectures=native",
    "RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX",
    "# nothing here needs a capability: not root, and the port is above 1024.",
    "CapabilityBoundingSet=",
    "UMask=0077",
    "# the app writes only under its own directory; anywhere else it writes",
    "# (a database, a cache) has to be listed here too, or the write fails.",
    `ReadWritePaths=/srv/${name}`,
  ];
  return [
    "[Unit]",
    `Description=${name} (borgo app)`,
    "After=network.target",
    "",
    "[Service]",
    `WorkingDirectory=/srv/${name}`,
    "# absolute path is systemd's rule, not borgo's: check yours with `command -v bun`.",
    "# the official installer writes ~/.bun/bin/bun, which is not readable by User=",
    "# below - copy or symlink it somewhere system-wide, or point this line at it.",
    "ExecStart=/usr/local/bin/bun run start",
    "Environment=NODE_ENV=production",
    `Environment=PORT=${port}`,
    `Environment=API_PORT=${apiPort}`,
    ...session,
    "# bun's outbound fetch pool defaults to 256, which ceilings concurrent",
    "# proxied requests - event streams above all - see docs/realtime.md",
    "Environment=BUN_CONFIG_MAX_HTTP_REQUESTS=16384",
    "Restart=on-failure",
    "User=www-data",
    "",
    ...hardening,
    "",
    "[Install]",
    "WantedBy=multi-user.target",
    "",
  ].join("\n");
}

export function composeYml({ port, secret }: DeployContext): string {
  // `:?` stops the deploy on a missing key instead of a 500 on every login;
  // an app with no key gets no line, or this file overrides a correct .env
  const session = secret
    ? [
        "      # read from the .env beside this file, which docker compose",
        "      # interpolates and the image never receives (.dockerignore",
        "      # excludes it). required on purpose: a missing key must stop the",
        "      # deploy, not turn up later as a 500 on every login.",
        '      SESSION_SECRET: "${SESSION_SECRET:?missing - create-borgo writes one into .env, or generate one with openssl rand -base64 48}"',
      ]
    : [
        "      # this app signs no sessions yet. adding borgo.SetSession later?",
        "      # it needs SESSION_SECRET (32+ random characters) or every session",
        "      # route answers 500 - put it in the .env beside this file and",
        '      # declare it here as: SESSION_SECRET: "${SESSION_SECRET:?missing}"',
      ];
  return [
    "services:",
    "  app:",
    "    build: .",
    "    ports:",
    `      - "${port}:${port}"`,
    "    environment:",
    "      NODE_ENV: production",
    `      PORT: "${port}"`,
    ...session,
    "      # bun's outbound fetch pool defaults to 256, which ceilings",
    "      # concurrent event streams - see docs/realtime.md",
    '      BUN_CONFIG_MAX_HTTP_REQUESTS: "16384"',
    "    restart: unless-stopped",
    // /healthz answers 200 with the api down - the state is in the body, so
    // a status-code probe never fires. docker marks unhealthy, never restarts
    "    healthcheck:",
    "      # /healthz answers 200 even when the api is down - the state is in",
    "      # the body. bun is the runtime image's own binary, so no curl needed.",
    `      test: ["CMD", "bun", "-e", "fetch('http://127.0.0.1:${port}/healthz').then(r=>r.text()).then(t=>process.exit(t.includes('\\"status\\":\\"ok\\"')?0:1)).catch(()=>process.exit(1))"]`,
    "      interval: 30s",
    "      timeout: 5s",
    "      start_period: 20s",
    "      retries: 3",
    "# nothing here persists yet, so there is no volume. swapping the in-memory",
    "# stores for a real database? the scaffolded Dockerfile already creates",
    "# /data owned by the image's user, so this is the whole change:",
    "#   environment:",
    "#     DB_PATH: /data/app.db",
    "#   volumes:",
    "#     - data:/data",
    "# volumes:",
    "#   data:",
    "",
  ].join("\n");
}

export const targets: Record<string, { file: string; render: (ctx: DeployContext) => string; next: (ctx: DeployContext) => string }> = {
  caddy: {
    file: "Caddyfile",
    render: caddyfile,
    next: () => "caddy run --config Caddyfile - local cert as written; for a real domain, set it and delete `tls internal`",
  },
  nginx: {
    file: "site.conf",
    render: nginxConf,
    next: ({ name }) => `set your domain and certs, then link it: /etc/nginx/sites-enabled/${name}.conf`,
  },
  systemd: {
    file: "borgo.service",
    render: systemdUnit,
    next: ({ name }) =>
      `copy to /etc/systemd/system/${name}.service, then: systemctl enable --now ${name}`,
  },
  compose: {
    file: "docker-compose.yml",
    render: composeYml,
    next: () => "docker compose up -d",
  },
};

// from the app's `.env`, never from the shell that ran `deploy init`: an
// exported PORT from another project would be baked into every generated file
function portOf(value: string | undefined, fallback: string): string {
  const n = Number(value);
  return value && /^\d+$/.test(value) && n >= 1 && n <= 65535 ? value : fallback;
}

export function projectContext(dir = "."): DeployContext {
  let name = "borgo-app";
  try {
    const pkg = JSON.parse(readFileSync(join(dir, "package.json"), "utf8")) as { name?: string };
    if (pkg.name) name = pkg.name.replace(/[^a-zA-Z0-9._-]+/g, "-").replace(/^-+|-+$/g, "") || name;
  } catch {}
  const env = envFile(dir);
  const secret = env.SESSION_SECRET;
  return {
    name,
    port: portOf(env.PORT, "3000"),
    apiPort: portOf(env.API_PORT, "3501"),
    secret: secret && secret.length >= SESSION_SECRET_MIN ? secret : null,
  };
}

// both ignore files: the unit is deployment-local (host paths, host user) and
// the file an operator hand-edits when they want an `Environment=` line
export function ensureIgnored(dir: string, ignoreFile: string, entry: string): "added" | "present" | "failed" {
  const path = join(dir, ignoreFile);
  let text = "";
  try {
    text = readFileSync(path, "utf8");
  } catch {}
  if (text.split("\n").some((line) => line.trim() === entry)) return "present";
  const gap = text && !text.endsWith("\n") ? "\n" : "";
  try {
    writeFileSync(path, `${text}${gap}# deployment-local, and never a place for a key\n${entry}\n`);
  } catch {
    return "failed";
  }
  return "added";
}

export function deployInit(target: string | undefined, force = false, dir = "."): number {
  console.log(`\n  ${banner("deploy")}\n`);
  const known = Object.keys(targets).join("|");
  if (!target || !targets[target]) {
    if (target) console.log(`  ${c.red(g.err)} unknown target "${target}"`);
    console.log(`  usage: borgo deploy init <${known}> [--force]\n`);
    return 1;
  }

  const { file, render, next } = targets[target];
  const path = join(dir, file);
  if (existsSync(path) && !force) {
    console.log(`  ${c.red(g.err)} ${file} already exists ${c.dim(`${g.dot} rerun with --force to overwrite`)}\n`);
    return 1;
  }

  const ctx = projectContext(dir);
  try {
    writeFileSync(path, render(ctx));
  } catch (error) {
    console.log(`  ${c.red(g.err)} cannot write ${file}: ${error instanceof Error ? error.message : error}\n`);
    return 1;
  }
  console.log(`  ${c.sage(g.ok)} ${file} ${c.dim(`${g.dot} ${target} config for ${ctx.name} on port ${ctx.port}`)}`);

  if (target === "systemd") {
    for (const ignoreFile of [".gitignore", ".dockerignore"]) {
      if (ensureIgnored(dir, ignoreFile, file) === "added") {
        console.log(`  ${c.sage(g.ok)} ${ignoreFile} ${c.dim(`${g.dot} ${file} added`)}`);
      }
    }
    // printed, not written: a terminal is not a file anything commits
    if (!ctx.secret) {
      console.log(`  ${c.terracotta(g.arrow)} no SESSION_SECRET in .env ${c.dim(`${g.dot} echo 'SESSION_SECRET=${randomSecret()}' >> .env`)}`);
    }
  }

  console.log(`  ${c.terracotta(g.arrow)} ${next(ctx)}\n`);
  return 0;
}
