import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { banner, c, g } from "./colors";
import { projectContext } from "./deploy";

export function manifest(name: string): string {
  return (
    JSON.stringify(
      {
        name,
        short_name: name.length > 12 ? name.slice(0, 12) : name,
        description: `${name}, a borgo app`,
        start_url: "/",
        scope: "/",
        display: "standalone",
        background_color: "#f7f0e3",
        theme_color: "#c06b45",
        icons: [
          { src: "/logo.svg", sizes: "any", type: "image/svg+xml", purpose: "any" },
          { src: "/icon-192.png", sizes: "192x192", type: "image/png" },
          { src: "/icon-512.png", sizes: "512x512", type: "image/png" },
        ],
      },
      null,
      2,
    ) + "\n"
  );
}

// a service worker reinstalls only when its own bytes change: this line is
// what `borgo build` rewrites to make them move
export const SW_STAMP_LINE = /^const BUILD = "[^"]*";$/m;

export const SW_UNSTAMPED = "unbuilt";

// documents are never cached: they are session-dependent, and a blanket
// document cache is how one user ends up looking at another user's page
export function serviceWorker(stamp: string = SW_UNSTAMPED): string {
  return `// generated by borgo pwa init - yours to edit
// caches the build output listed in /assets/precache.json. BUILD is rewritten
// by every production build - a worker whose bytes never change is a worker
// the browser never reinstalls - so leave that line where borgo can find it.

const BUILD = ${JSON.stringify(stamp)};
const CACHE = "app-" + BUILD;
const MANIFEST = "/assets/precache.json";

self.addEventListener("install", (event) => {
  event.waitUntil(
    fetch(MANIFEST, { cache: "no-store" })
      .then((res) => res.json())
      .then(({ assets }) => caches.open(CACHE).then((cache) => cache.addAll(assets))),
  );
  // take over as soon as this worker is ready rather than waiting for every
  // tab to close; the new cache is already filled by the time it happens
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(
          keys
            .filter((key) => key.startsWith("app-") && key !== CACHE)
            .map((key) => caches.delete(key)),
        ),
      )
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (event) => {
  const url = new URL(event.request.url);
  // build output only: same origin, under /assets, and never the manifest
  // itself - a stale manifest would pin the app to an old stamp forever
  if (
    event.request.method !== "GET" ||
    url.origin !== location.origin ||
    !url.pathname.startsWith("/assets/") ||
    url.pathname === MANIFEST
  ) {
    return;
  }
  // scoped to this build's cache on purpose: caches.match() with no cacheName
  // searches every cache in CacheStorage, in creation order, oldest first - so
  // a cache activate has not pruned yet answers for the deploy that owns it
  event.respondWith(
    caches
      .open(CACHE)
      .then((cache) => cache.match(event.request))
      .then((hit) => hit ?? fetch(event.request)),
  );
});
`;
}

// null: the stamp line is gone, a hand-written worker borgo must not touch
export function restampServiceWorker(source: string, stamp: string): string | null {
  if (!SW_STAMP_LINE.test(source)) return null;
  return source.replace(SW_STAMP_LINE, `const BUILD = ${JSON.stringify(stamp)};`);
}

// a missing or hand-written worker is not a build failure
export function stampWorkerFile(stamp: string, dir = "."): boolean {
  const path = join(dir, "public", "sw.js");
  let source: string;
  try {
    source = readFileSync(path, "utf8");
  } catch {
    return false;
  }
  const next = restampServiceWorker(source, stamp);
  if (next === null || next === source) return false;
  try {
    writeFileSync(path, next);
  } catch {
    return false;
  }
  return true;
}

// a worker written after a build starts from that build's stamp, installable now
function builtStamp(dir: string): string {
  try {
    const parsed = JSON.parse(readFileSync(join(dir, "public", "assets", "precache.json"), "utf8"));
    return typeof parsed?.stamp === "string" ? parsed.stamp : SW_UNSTAMPED;
  } catch {
    return SW_UNSTAMPED;
  }
}

export function pwaInit(force = false, dir = "."): number {
  console.log(`\n  ${banner("pwa")}\n`);
  const ctx = projectContext(dir);
  const publicDir = join(dir, "public");
  try {
    mkdirSync(publicDir, { recursive: true });
  } catch {}

  const files: Array<[string, string]> = [
    ["manifest.webmanifest", manifest(ctx.name)],
    ["sw.js", serviceWorker(builtStamp(dir))],
  ];

  const existing = files.filter(([f]) => existsSync(join(publicDir, f))).map(([f]) => f);
  if (existing.length && !force) {
    console.log(
      `  ${c.red(g.err)} public/${existing.join(", public/")} already exists ${c.dim(`${g.dot} rerun with --force to overwrite`)}\n`,
    );
    return 1;
  }

  for (const [file, contents] of files) {
    try {
      writeFileSync(join(publicDir, file), contents);
    } catch (error) {
      console.log(
        `  ${c.red(g.err)} cannot write public/${file}: ${error instanceof Error ? error.message : error}\n`,
      );
      return 1;
    }
    console.log(`  ${c.sage(g.ok)} public/${file}`);
  }

  console.log(`
  ${c.bold("two edits left")}, both one line:

  ${c.dim("1.")} in ${c.bold("index.html")}, inside <head>:
     ${c.terracotta('<link rel="manifest" href="/manifest.webmanifest" />')}

  ${c.dim("2.")} in a page or layout that hydrates:
     ${c.terracotta('import { registerServiceWorker } from "borgo-framework";')}
     ${c.terracotta("useEffect(() => registerServiceWorker(), []);")}

  ${c.dim(`the worker only runs in production builds ${g.dot} icons: add public/icon-192.png and icon-512.png`)}
  ${c.terracotta(g.arrow)} docs: https://github.com/LuigiDavideMicca/borgo/blob/main/docs/pwa.md
`);
  return 0;
}
