// generated by borgogen - do not edit
package api

import "github.com/LuigiDavideMicca/borgo"

func init() {
	borgo.Handle("GET /api/holder", GetHolder)
	borgo.Handle("GET /api/node", GetNode)
	borgo.Handle("GET /api/outer", GetOuter)
	borgo.Handle("GET /api/outermap", GetOuterMap)
	borgo.Handle("GET /api/outers", GetOuters)
}
