// generated by borgogen - do not edit

export interface Plain {
  name: string;
}

// Slug as encoding/json reads it: the request body it
// accepts, which is not the response it writes - something inside it
// carries one side of the conversion without the other.
export interface Slug$Request {
  raw: string;
}

// Create as encoding/json reads it: the request body it
// accepts, which is not the response it writes - something inside it
// carries one side of the conversion without the other.
export interface Create$Request {
  slug: Slug$Request;
  stamp: unknown;
  note: string;
}

export interface Stamp {
  unix: number;
}

export interface Create {
  slug: string;
  stamp: Stamp;
  note: string;
}

declare module "borgo-framework" {
  interface ApiRoutes {
    "POST /api/plain": { response: Plain; request: Plain };
    "POST /api/things": { response: Create; request: Create$Request };
  }
}

export {};
