// generated by borgogen - do not edit

// Plain as encoding/json reads it, which is not
// the response it writes: a field the decoder never receives is not an
// error, and neither is one that arrives null, so every property below
// is optional and admits null whatever its Go type is.
export interface Plain$Request {
  name?: string | null;
}

export interface Plain {
  name: string;
}

// Slug as encoding/json reads it, which is not
// the response it writes: a field the decoder never receives is not an
// error, and neither is one that arrives null, so every property below
// is optional and admits null whatever its Go type is.
export interface Slug$Request {
  raw?: string | null;
}

// Create as encoding/json reads it, which is not
// the response it writes: a field the decoder never receives is not an
// error, and neither is one that arrives null, so every property below
// is optional and admits null whatever its Go type is.
export interface Create$Request {
  slug?: Slug$Request | null;
  stamp?: unknown | null;
  note?: string | null;
}

export interface Stamp {
  unix: number;
}

export interface Create {
  slug: string;
  stamp: Stamp;
  note: string;
}

declare module "borgo-framework" {
  interface ApiRoutes {
    "POST /api/plain": { response: Plain; request: Plain$Request };
    "POST /api/things": { response: Create; request: Create$Request };
  }
}

export {};
