// generated by borgogen - do not edit

export interface Child {
  name: string;
  id: number;
}

export interface Deep {
  a?: number;
  c?: number;
  d: number;
}

export interface Diamond {
  a1: number;
  b1: number;
}

export interface Doc {
  id: number;
  name: string;
  title: string;
}

export interface PtrOuter {
  a?: number;
  b: number;
}

export interface Tie {
  y: number;
}

declare module "borgo-framework" {
  interface ApiRoutes {
    "GET /api/child": { response: Child };
    "GET /api/deep": { response: Deep };
    "GET /api/diamond": { response: Diamond };
    "GET /api/doc": { response: Doc };
    "GET /api/ptrouter": { response: PtrOuter };
    "GET /api/tie": { response: Tie };
  }
}

export {};
