// generated by borgogen - do not edit

export interface resp {
  at: string;
}

declare module "borgo-framework" {
  interface ApiRoutes {
    "GET /api/stamped": { response: resp };
  }
}

export {};
