// generated by borgogen - do not edit
package api

import "github.com/LuigiDavideMicca/borgo"

func init() {
	borgo.Handle("GET /api/nested/either", GetEither)
	borgo.Handle("GET /api/nested/one", GetNested)
	borgo.Handle("POST /api/nested/push", DoPush)
}
