// generated by borgogen - do not edit

// Inner as encoding/json reads it, which is not
// the response it writes: a field the decoder never receives is not an
// error, and neither is one that arrives null, so every property below
// is optional and admits null whatever its Go type is.
export interface Inner$Request {
  a?: number | null;
}

// Every as encoding/json reads it, which is not
// the response it writes: a field the decoder never receives is not an
// error, and neither is one that arrives null, so every property below
// is optional and admits null whatever its Go type is.
export interface Every$Request {
  flag?: boolean | null;
  count?: number | null;
  ratio?: number | null;
  name?: string | null;
  ptr?: string | null;
  list?: Array<string> | null;
  fixed?: Array<string> | null;
  dict?: Record<string, string> | null;
  nested?: Inner$Request | null;
  blob?: string | null;
  at?: string | null;
  amount?: number | null;
  free?: unknown | null;
  code?: string | null;
  opt?: string | null;
  quoted?: string | null;
}

export interface Inner {
  a: number;
}

export interface Every {
  flag: boolean;
  count: number;
  ratio: number;
  name: string;
  ptr: string | null;
  list: Array<string> | null;
  fixed: Array<string>;
  dict: Record<string, string> | null;
  nested: Inner;
  blob: string | null;
  at: string;
  amount: number;
  free: unknown;
  code: string;
  opt?: string;
  quoted: string;
}

// Loose as encoding/json reads it, which is not
// the response it writes: a field the decoder never receives is not an
// error, and neither is one that arrives null, so every property below
// is optional and admits null whatever its Go type is.
export interface Loose$Request {
  ptr?: string | null;
}

export interface Loose {
  ptr?: string | null;
}

declare module "borgo-framework" {
  interface ApiRoutes {
    "POST /api/every": { response: Every; request: Every$Request };
    "POST /api/loose": { response: Loose; request: Loose$Request };
    "POST /api/tags": { response: Array<string> | null; request: Array<string> | null };
  }
}

export {};
