// generated by borgogen - do not edit

export interface Hop {
  next: Ring;
}

export type Ring = Array<Hop> | null;

export type Tree = Record<string, Tree> | null;

export interface Wallet {
  balance: number;
}

declare module "borgo-framework" {
  interface ApiRoutes {
    "GET /api/ring": { response: Ring };
    "GET /api/tree": { response: Tree };
    "GET /api/wallet": { response: Wallet };
  }
}

export {};
