// generated by borgogen - do not edit

export interface Ack {
  ok: boolean;
}

export interface Note {
  text: string;
}

export interface Audit {
  at: string;
}

declare module "borgo-framework" {
  interface ApiRoutes {
    "POST /api/say": { response: Ack };
  }
  interface WsEvents {
    "room/audit": Audit;
    "room/note": Note;
  }
}

export {};
