// generated by borgogen - do not edit

export interface resp {
  at: string;
}

export interface stamp {
  nano: number;
}

export interface ApiResp {
  at: stamp;
}

declare module "borgo-framework" {
  interface ApiRoutes {
    "GET /api/one": { response: resp };
    "GET /api/two": { response: ApiResp };
  }
}

export {};
