// generated by borgogen - do not edit

export interface Wrapped {
  b: string;
}

export interface Inline {
  a: number;
}

declare module "borgo-framework" {
  interface ApiRoutes {
    "GET /api/authedinline": { response: Wrapped };
    "GET /api/inline": { response: Inline };
    "GET /api/opaque": { response: unknown };
    "GET /api/wrapped": { response: Wrapped };
  }
}

export {};
