// generated by borgogen - do not edit

export interface PM {
  x: number;
}

export interface Outer {
  p: PM;
}

// Outer as encoding/json writes it where the value is
// addressable - a slice element, or anything behind a pointer - so the
// pointer-receiver marshalers inside it do run.
export interface Outer$Addressable {
  p: unknown;
}

export interface ArrBox {
  a: Array<Outer>;
}

// ArrBox as encoding/json writes it where the value is
// addressable - a slice element, or anything behind a pointer - so the
// pointer-receiver marshalers inside it do run.
export interface ArrBox$Addressable {
  a: Array<Outer$Addressable>;
}

export interface Deref {
  p?: unknown;
  b: number;
}

export interface Holder {
  plain: Outer;
  many: Array<Outer$Addressable> | null;
  keyed: Record<string, Outer> | null;
  ptr: Outer$Addressable | null;
  arr: Array<Outer>;
  arrin: Array<Array<Outer$Addressable>> | null;
  box: ArrBox;
  boxes: Array<ArrBox$Addressable> | null;
  deref: Deref;
  derefs: Array<Deref> | null;
  both: string;
  bothin: Array<unknown> | null;
}

// Node as encoding/json writes it where the value is
// addressable - a slice element, or anything behind a pointer - so the
// pointer-receiver marshalers inside it do run.
export interface Node$Addressable {
  p: unknown;
  next: Node$Addressable | null;
}

export interface Node {
  p: PM;
  next: Node$Addressable | null;
}

declare module "borgo-framework" {
  interface ApiRoutes {
    "GET /api/holder": { response: Holder };
    "GET /api/node": { response: Node };
    "GET /api/outer": { response: Outer };
    "GET /api/outermap": { response: Record<string, Outer> | null };
    "GET /api/outers": { response: Array<Outer$Addressable> | null };
  }
}

export {};
